#!/bin/bash

# Get system information
USERNAME=$(whoami)
DATE=$(date)
HOSTNAME=$(hostname)
. /etc/os-release
OS="$PRETTY_NAME"
UPTIME=$(uptime -p)

# Get hardware information
CPU=$(lscpu | grep "Model name" | awk -F ': ' '{print $2}')
RAM=$(free -h | awk '/^Mem:/ {print $2}')
DISKS=$(lsblk -o NAME,MODEL,SIZE | grep -E '^sd|^nvme' | awk '{print $1": "$2" "$3}')
VIDEO=$(lspci | grep -i 'vga' | cut -d ':' -f3 | sed 's/^ //')

# Get network information
FQDN=$(hostname --fqdn)
HOST_IP=$(ip a | grep "inet " | grep -v "127.0.0.1" | awk '{print $2}' | cut -d'/' -f1)
GATEWAY=$(ip route | grep default | awk '{print $3}')
DNS=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}')

# Get system status
LOGGED_USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd ', ' -)
DISK_SPACE=$(df -h --output=target,avail | awk 'NR>1 {print $1 " " $2}')
PROCESS_COUNT=$(ps aux --no-headers | wc -l)
LOAD_AVG=$(uptime | awk -F'load average: ' '{print $2}')
LISTENING_PORTS=$(ss -tuln | awk 'NR>1 {print $5}' | awk -F':' '{print $NF}' | sort -n | uniq | paste -sd ', ' -)
UFW_STATUS=$(sudo ufw status | grep -q "Status: active" && echo "enabled" || echo "disabled")

# Generate report
cat <<EOF

System Report generated by Shani B K, $DATE

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
RAM: $RAM
Disk(s):
$DISKS
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_IP
Gateway IP: $GATEWAY
DNS Server: $DNS

System Status
-------------
Users Logged In: $LOGGED_USERS
Disk Space:
$DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVG
Listening Network Ports: $LISTENING_PORTS
UFW Status: $UFW_STATUS

EOF

